#!/usr/bin/python
import random, sys

#choose default dictionary file used
dict = '/usr/share/dict/words'

#make a list of words from the dictionary file
words = []
with open(dict) as f:
	words = [entry.strip() for entry in f]

if len(sys.argv) > 1:
	try:
		num = int(sys.argv[1])
		if num > 0:
			for x in range(num):
			#pick a bunch of words from the dictionary
				goodword = random.choice(words)
				badword = ""
				for y in goodword:
				#go letter by letter and mutate words
					tmp = y
					cointoss = random.randint(0,1)
					if cointoss:
						tmp = tmp.lower()
					else:
						tmp = tmp.upper()
					if tmp.lower() in "aeiou":
						tmp = random.choice("aeiou")
					tmp = tmp*random.randint(1,3)
					badword += tmp
				#print goodword	#in case you'd like to check
				print badword
		else:
			print "Please specify a positive integer."
	except ValueError:
		print "Please specify a positive integer argument."
else:
	print "Usage: barrage n\n Creates n mispelled words where n is a positive integer."
